# Generated by Django 5.0 on 2023-12-09 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('nascimento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('esporte', models.CharField(max_length=255)),
                ('isOpen', models.BooleanField()),
                ('data_fechamento', models.DateTimeField(null=True)),
                ('data_abertura', models.DateTimeField()),
                ('semestre', models.FloatField(help_text='Ex.: 2023.2')),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
        migrations.AddField(
            model_name='aluno',
            name='atestado_apt',
            field=models.CharField(help_text='Link para o documento', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='user_cpf',
            field=models.OneToOneField(default=123456789, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.usuario'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.aluno')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.turma')),
                ('prof_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('matric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.matricula')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.turma'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user_cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.usuario')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.administrador')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='atestado_apt_validado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.administrador'),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField()),
                ('turma_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.turma')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Leciona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.turma')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.professor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='frequencia',
            constraint=models.UniqueConstraint(fields=('matric_id', 'data'), name='unique_frequencia'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno_cpf', 'turma_id', 'prof_cpf'), name='unique_matricula'),
        ),
    ]
