# Generated by Django 5.0 on 2023-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
