# Generated by Django 5.0 on 2023-12-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_turma_vagas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leciona',
            old_name='prof',
            new_name='prof_cpf',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='prof',
            new_name='prof_cpf',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='isOpen',
            new_name='is_open',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='esporte',
            new_name='modalidade',
        ),
        migrations.AddField(
            model_name='turma',
            name='horario',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
