# Generated by Django 5.0 on 2023-12-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_prof_leciona_prof_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leciona',
            name='data_termino',
            field=models.DateTimeField(null=True),
        ),
    ]
