# Generated by Django 5.0 on 2023-12-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_leciona_data_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atestado_apt_validado_em',
            field=models.DateTimeField(null=True),
        ),
    ]
