# Generated by Django 5.0 on 2023-12-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_aluno_atestado_apt_validado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='siape',
            field=models.IntegerField(null=True),
        ),
    ]
