# Generated by Django 5.0 on 2023-12-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_professor_siape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='siape',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
