# Generated by Django 5.0 on 2023-12-14 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_professor_siape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='atestado_apt_validado_em',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 749254, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 764254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leciona',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 754254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leciona',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 754254, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 753254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 752256, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_fechamento',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 752256, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 0, 8, 697249, tzinfo=datetime.timezone.utc)),
        ),
    ]
