# Generated by Django 5.0 on 2023-12-14 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_aluno_atestado_apt_validado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='atestado_apt_validado_em',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leciona',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 6, 25, 586087, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leciona',
            name='data_termino',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 6, 25, 586087, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 6, 25, 585087, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_fechamento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.DateTimeField(),
        ),
    ]
