# Generated by Django 5.0 on 2023-12-14 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_aluno_atestado_apt_validado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leciona',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 4, 36, 55, 321373, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 4, 36, 55, 320374, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 4, 36, 55, 320374, tzinfo=datetime.timezone.utc)),
        ),
    ]
