# Generated by Django 5.0 on 2023-12-14 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_leciona_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leciona',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 4, 38, 49, 995520, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 4, 38, 49, 995520, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_abertura',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 4, 38, 49, 994520, tzinfo=datetime.timezone.utc)),
        ),
    ]
