# Generated by Django 5.0 on 2023-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_remove_professor_siape'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atestado_apt_esperando_validacao',
            field=models.BooleanField(default=False),
        ),
    ]
