# Generated by Django 5.0 on 2023-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_frequencia_presente'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leciona',
            constraint=models.UniqueConstraint(fields=('turma_id', 'prof_cpf'), name='unique_leciona'),
        ),
    ]
